const Categories = [
    'Hành động',
    'Phiêu lưu',
    'Hài hước',
    'Drama',
    'Fantasy',
    'Khoa học viễn tưởng',
    'Siêu nhiên',
    'Harem',
    'Trường học',
    'Trinh thám',
    'Xuyên không',
    'Ngôn tình',
    'Dị giới',
    'Kinh dị',
    'Sáng tạo',
    'Lịch sử',
    'Game',
    'Đam mỹ',
    'Shoujo',
    'Shounen',
    'Webtoon',
    'Manhua',
    'Manhwa',
    'Truyện tranh Việt',
    'One shot',
    'Ecchi',
    'Bí ẩn',
    'Yuri',
    'Yaoi',
    'Lãng mạn',
    'Tâm lý',
    'Hài hước',
    'Đời thường',
    'Thể thao',
    'Bi kịch',
    'Isekai',
    'Josei',
    'Quân sự',
    'Mecha',
    'Âm nhạc',
    '18+',
    'Siêu anh hùng',
];

export default Categories;
